baseURL = "https://eliaswatson.dev"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Elias Watson"
theme = "anubis2"

[pagination]
pagerSize = 5

[params.author]
name = "Elias Watson"
email = "me@eliaswatson.dev"
location = "United States of America"

[params]
description = "Ramblings of Elias Watson"
dateFormat = "2006-01-02"
mainSections = ["posts", "projects"]
customCSS = ["c64.css"]
style = "auto"
readMore = false
readNextPosts = 3
copyCodeButton = true
rssAsSocialIcon = true

[[params.social]]
id = "github"
url = "https://github.com/EliasWatson"

[[params.social]]
id = "linkedin"
url = "https://www.linkedin.com/in/elias-watson"

[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 2

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 3

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 4

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = 'base16-snazzy' # Highlight.js style
